### ISSUE TITLE
Pip error

### ISSUE THREAD

**Issue by rsalek** [althonos/mzml2isa#11]
Command "git clone -q git://github.com/althonos/mzml2isa /var/folders/hd/d0qt8r1922l74xggrtzl64h00000gn/T/pip-SxspF7-build" failed with error code 128 in None

**Comment by althonos** [comment]
What was the pip command you ran ?

**Comment by rsalek** [comment]
Yes

**Comment by rsalek** [comment]
AlsoI tried: 
pip install mzml2isa-qt
Collecting mzml2isa-qt
  Using cached mzml2isa-qt-0.3.0.zip
    Complete output from command python setup.py egg_info:
    error: this is a python3 program.
    
    -------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/hd/d0qt8r1922l74xggrtzl64h00000gn/T/pip-build-JY5p9K/mzml2isa-qt/

  -------------------------------------
on my mac have python3 for ver 3+ and python for version 2.7, seems pip script uses python .

**Comment by althonos** [comment]
> pip install git+git://github.com/althonos/mzml2isa
> Collecting git+git://github.com/althonos/mzml2isa
> Cloning git://github.com/althonos/mzml2isa to /var/folders/hd/d0qt8r1922l74xggrtzl64h00000gn/T/pip-aIk50u-build
> fatal: unable to connect to github.com:
> github.com[0: 192.30.253.112]: errno=Connection refused
> 
> Command "git clone -q git://github.com/althonos/mzml2isa /var/folders/hd/d0qt8r1922l74xggrtzl64h00000gn/T/pip-aIk50u-build" failed with error code 128 in None

This seems to be a github issue, try this command instead:
`pip install git+https://github.com/althonos/mzml2isa`

> AlsoI tried:
> pip install mzml2isa-qt
> Collecting mzml2isa-qt
> Using cached mzml2isa-qt-0.3.0.zip
> Complete output from command python setup.py egg_info:
> error: this is a python3 program.
 
Should be reported here: https://github.com/althonos/mzml2isa-qt/issues :smile:

Actually, this is because mzml2isa-qt is Py3 only, so you should use the `pip3` command instead of `pip` :smile:

**Comment by rsalek** [comment]
Thx - done, see another issue,  now in the right place 👍
