### ISSUE TITLE
Apparently stuck on multi-thread deadlock

### ISSUE THREAD

**Issue by pcm32** [althonos/mzml2isa#16]
Hi there!

I installed mzml2isa on both macOS and ubuntu using pip. Specifically, I tried mzml2isa versions 0.4.24 and 0.4.25. When I run it with the test data provided with the Galaxy wrapper (here)[https://github.com/ISA-tools/mzml2isa-galaxy/tree/master/galaxy/mzml2isa/test-data] it always seems to get stuck without in some sort of threading deadlock, which no CPU usage by any of the parallel threads. The command I execute is:

```bash
mzml2isa -i ~/Downloads/metabolomics_study -o output -s test_study
```

I tried turning off parallel executions with `-j 1`, but still plenty of parallel processes (with no CPU usage at all) were started. The program stays "running" "for ever", but there is no output and no CPU/IO usage at all, by any of the python processes generated.

Whenever you press Ctrl-c in the middle of the execution, you see tracebacks related to multiprocessing queues and locks, like:

```
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/queues.py", line 115, in get
    self.run()
  File "/Users/myuser/Development/mzml2isa-galaxy/.mzml2isa/lib/python2.7/site-packages/pronto/parser/obo.py", line 29, in run
    self._rlock.acquire()
    term = self.queue.get()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/queues.py", line 115, in get
KeyboardInterrupt
    self._rlock.acquire()
KeyboardInterrupt
    self.run()
  File "/Users/myuser/Development/mzml2isa-galaxy/.mzml2isa/lib/python2.7/site-packages/pronto/parser/obo.py", line 29, in run
    term = self.queue.get()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/queues.py", line 115, in get
    self._rlock.acquire()
KeyboardInterrupt
    res = self._recv()
KeyboardInterrupt
```

Thanks!
Pablo

**Comment by althonos** [comment]
Hi !
Well, I think the CPU spawns are created because of pronto ontology
parsing, but I'm not sure why there would be any deadlock at all... I'll
investigate that.
What version of python did you use ?

**Comment by rsalek** [comment]
we saw obo.py Pablo, is some out going request could be block by firewall?  does obo.py do that, Martin?

**Comment by althonos** [comment]
Obo.py is the OBO parser of pronto, and as a first it tries to connect to
the online repository containing the latest psi-ms ontology.
In theory in case of timeout or error it should fall back to the local
psi-ms.obo file, but it may happen that your firewall blocks the connection
without properly closing it, therefore causing an infinite loop...
I've never underwent such a situation, though, so i suspect your proxy is
in cause here.

**Comment by pcm32** [comment]
hehehe, sorry to disappoint you, but there is no proxy/firewall in question here (and if it gives you peace of mind, the same happens on different networks)... I bet that there is a race between threads producing some deadlock.

using python 2.7.10

and did try it as well on different machines on different networks, same result, and interrupt showed that process was on the same classes. Have you tried it?

**Comment by althonos** [comment]
I'll try, but what's surprising is that this seems to occur only with the
mzml2isa-galaxy, not with mzml2isa...
The deadlock I had was with an old version of pronto, but this should be
fixed now, are you sure you're using the latest version of everything ?
Can you try Python3 or are you stuck with Python2 ?

**Comment by Tomnl** [comment]
Hi all,

If it is using mzml2isa-galaxy the mzml2isa package is loaded from bioconda that uses at the moment mzml2isa v0.4.24.

https://github.com/ISA-tools/mzml2isa-galaxy/tree/master/packages/package_mzml2isa_0_4_24

So I think we have to add the new version of mzml2isa to bioconda and update the mzml2isa code.

Perhaps it will fix the problem.

**Comment by pcm32** [comment]
Hi, we intend to use it within Galaxy, so we cannot move to python 3. As I mentioned, I tried both the galaxy wrapped call and the direct mzml2isa call (that is the one that I tried in most places actually), so I wouldn't say that it happens only with mzml2isa-galaxy. I'm installing everything with pip after reinstalling the newest pip version, always on a new virtualenv (so is the closest you can get to a fresh python install).

Maybe pronto is having a regression! Which version of pronto was giving the issue?

Thanks for checking.

**Comment by pcm32** [comment]
@Tomnl thanks for chipping in. Our galaxy doesn't use bioconda, we have a setup that runs on Kubernetes, we explicitly set the container, plus other settings, were things run. As I have clarified above, this is not an issue of it running within the galaxy wrapper, I have reproduced the problem through direct calls to the mzml2isa python script (as shown above), which is installed through the expected pip calls, no bioconda in the middle.

**Comment by althonos** [comment]
v0.3.3, I tried a custom multiprocessing.Queue as a workaround for MacOSX not having a proper semaphore API but in the end it would cause either deadlocks or inconsistant number of terms, so I changed the implementation and now 0.4.1 should be safe of that. But I know py2 is always giving me headaches compared to py3, as sometimes I get issues out of nowhere explicitly with py2... 

I made a hotfix [mzml2isa4py2.tar.gz](https://github.com/althonos/mzml2isa/files/504249/mzml2isa4py2.tar.gz), try to install it and tell me if it works, I did a quick fix but py2 will hopefully start working again.

**Comment by pcm32** [comment]
Thanks for looking at this so promptly Martin! with the version provided, it works like a charm! I should mention that the issue comes up not only on macOS but also on ubuntu. Do you intend to push these changes to the pip installable version? Let me know to rebuild our container when that is available and try again!

**Comment by althonos** [comment]
Yes, I'll do it as a workaround, I'm not happy with the way it works but
until then...

**Comment by pcm32** [comment]
Thanks Martin for your hard work! My two cents on this would be that a tool like this doesn't really need any multithreading. There is always a trade off when writing multithreaded code in terms of development/debugging complexity, and sometimes for a tool that does its work fairly quickly, is not worth it. Additionally, if your tool opens too many threads to read different mzml files, it could very easily see its performance degraded due to the IO wait (many processes trying to access the disk for reading at the same time).  What is 'too many' will depend on the type of drive that you'r accessing. At the very least, I would suggest providing a flag on the command line argument that allows the user to control the number of threads/processes opened.

**Comment by althonos** [comment]
Actually, it's not mzml2isa that opens threads, but the ontology handler I
wrote. This was made to avoid having to store the whole ontology in memory
to be able to parse, because some can be really large (I'm looking at you
ChEBI), hence a consumer/worker structure.

But after some checks I realized it's NOT the multiprocessing that cause
"infinite loading times", but a very badly written method inside my code
that uses dictionnary comprehension which Python2 may not like... Every
KeyboardInterrupt had the traceback show me it was stuck in that method :)

Anyway, fix was pushed, I'll just wait for Travis before packaging it and
then that should work again I hope :)

**Comment by althonos** [comment]
Hi Pablo, PyPI now host mzml2isa v0.4.28, so I you can repackage it if you want.
