### ISSUE TITLE
Log/error message or directly exit(1) if no mzml's are found in the zip/tar file

### ISSUE THREAD

**Issue by pcm32** [althonos/mzml2isa#19]
I tried the tool with a TAR/Zip file that I thought that contained *.mzml files, however this wasn't the case. mzml2isa didn't fail nor generated any logging/error message saying that it had been provided a compressed files with no mzML files. I would suggest that there is either a flag for checking this or a message is printed so that the user knows that it is feeding a file with no mzMLs. Thanks!

**Comment by althonos** [comment]
Hi @pcm32,
actually there is one (absence of mzML / imzML in source dir / archive will raise a UserWarning) but I had left the warning control argument default level on ignore for debugging purposes, and that meant you couldn't see the flag :)
So now it will raise a warning, but if you want to completely fail the conversion use the `-W error` argument with the command line to raise a proper error.
